// // src/lib/mock-data.ts

// import type {
//   Lecture,
//   Review,
//   Chapter,
//   Lesson,
//   Question,
//   Level,
//   Category,
// } from '@/features/lectures/types';

// // 현재 유저
// export const currentUser = {
//   id: 'u1',
//   name: '김철수',
//   email: 'chulsoo@example.com',
//   role: 'MEMBER', // currentUser의 role -> "MEMBER" 로 변경 ("MEMBER" 아니면 "ADMIN"이 들어갑니다.)
// };

// // categories도 위의 카테고리 타입에 맞게 수정.
// export const categories = [
//   { id: 'c1', name: '전체', value: 'ALL' },
//   { id: 'c2', name: '프론트엔드', value: 'FRONTEND' },
//   { id: 'c3', name: '백엔드', value: 'BACKEND' },
//   { id: 'c4', name: 'AI', value: 'AI' },
//   { id: 'c5', name: '게임', value: 'GAME' },
// ];

// //  Lecture 전체 통합, 타입에 맞게 수정.
// export const lectures: Lecture[] = [
//   {
//     id: 'lecture-1',
//     title: 'Next.js 15 완벽 가이드: 프로덕션 레벨 앱 만들기',
//     creatorId: 'inst-1',
//     creatorName: '이영희',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 3420,
//     thumbnail:
//       'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
//     category: 'FRONTEND',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-03-15T09:00:00Z',
//     updatedAt: '2024-03-20T09:00:00Z',
//     description:
//       '최신 Next.js 15의 모든 기능을 마스터하고 실제 상용 서비스를 구축해보는 실전 강의입니다.',
//     curriculum: [
//       {
//         id: 'chapter-1',
//         title: 'Next.js 소개 및 환경 설정',
//         lessons: [
//           {
//             id: 'l-1-1',
//             title: 'Next.js란 무엇인가?',
//             duration: '10:00',
//             type: 'VIDEO',
//             videoUrl:
//               'https://www.youtube.com/embed/bClgGbYfeWE?si=gEN9PBOd0EGJAnn_',
//           },
//           {
//             id: 'l-1-2',
//             title: '개발 환경 설정하기',
//             duration: '15:30',
//             type: 'VIDEO',
//             videoUrl:
//               'https://www.youtube.com/embed/DHAiyJrX7t4?si=miV4-Uo_EjTyaWAc',
//           },
//         ],
//       },
//       {
//         id: 'chapter-2',
//         title: 'App Router 기초',
//         lessons: [
//           {
//             id: 'l-2-1',
//             title: 'Routing 기본',
//             duration: '12:45',
//             type: 'VIDEO',
//             videoUrl:
//               'https://www.youtube.com/embed/bClgGbYfeWE?si=gEN9PBOd0EGJAnn_',
//           },
//           {
//             id: 'l-2-2',
//             title: 'Layouts & Templates',
//             duration: '18:20',
//             type: 'VIDEO',
//             videoUrl:
//               'https://www.youtube.com/embed/DHAiyJrX7t4?si=miV4-Uo_EjTyaWAc',
//           },
//           {
//             id: 'l-2-3',
//             title: '퀴즈: App Router 이해도 확인',
//             type: 'QUIZ',
//             questions: [
//               {
//                 id: 'q1',
//                 question: 'App Router는 pages 디렉토리를 대체한다.',
//                 answer: 'O',
//               },
//               {
//                 id: 'q2',
//                 question: 'Server Components는 클라이언트에서 렌더링된다.',
//                 answer: 'X',
//               },
//               {
//                 id: 'q3',
//                 question: 'layout.tsx는 해당 경로의 하위 페이지에 공유된다.',
//                 answer: 'O',
//               },
//             ],
//           },
//         ],
//       },
//     ],
//   },
//   {
//     id: 'lecture-2',
//     title: 'UI/UX 디자인 마스터 클래스: 피그마 기초부터 심화까지',
//     creatorId: 'inst-2',
//     creatorName: '박지성',
//     price: 0,
//     rating: 4.8,
//     enrollmentCount: 2150,
//     thumbnail:
//       'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
//     category: 'GAME', // design → 임시로 GAME
//     level: 'BEGINNER',
//     createdAt: '2024-02-10T14:30:00Z',
//     updatedAt: '2024-02-11T14:30:00Z',
//     description: '피그마 툴 사용법부터 앱 디자인 프로젝트까지 진행합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-3',
//     title: '실전 마케팅 전략: 0원으로 시작하는 그로스 해킹',
//     creatorId: 'inst-3',
//     creatorName: '최민수',
//     price: 0,
//     rating: 4.7,
//     enrollmentCount: 1890,
//     thumbnail:
//       'https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=2074&auto=format&fit=crop',
//     category: 'AI', // marketing → 임시로 AI
//     level: 'ADVANCED',
//     createdAt: '2024-01-20T11:00:00Z',
//     updatedAt: '2024-02-01T11:00:00Z',
//     description: '실전 그로스 해킹 전략을 배웁니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-4',
//     title: '타입스크립트 핸드북: 안전한 자바스크립트 작성하기',
//     creatorId: 'creator-4',
//     creatorName: '김철수',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 5600,
//     thumbnail:
//       'https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=2128&auto=format&fit=crop',
//     category: 'FRONTEND',
//     level: 'BEGINNER',
//     createdAt: '2023-12-05T10:15:00Z',
//     updatedAt: '2023-12-05T10:15:00Z',
//     description:
//       '자바스크립트 개발자라면 필수로 알아야 할 타입스크립트. 기초 문법부터 고급 타입 추론까지 완벽하게 정리해드립니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-5',
//     title: '비즈니스 영어 이메일 작성법',
//     creatorId: 'creator-5',
//     creatorName: 'Sarah Kim',
//     price: 0,
//     rating: 4.6,
//     enrollmentCount: 1200,
//     thumbnail:
//       'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?q=80&w=2070&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'BEGINNER',
//     createdAt: '2024-03-01T09:30:00Z',
//     updatedAt: '2024-03-01T09:30:00Z',
//     description:
//       '글로벌 비즈니스 환경에서 통하는 세련된 영어 이메일 작성법. 상황별 템플릿과 필수 표현을 학습합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-6',
//     title: '실전 리액트 프로그래밍: 리덕스부터 MobX까지',
//     creatorId: 'creator-6',
//     creatorName: '김태희',
//     price: 0,
//     rating: 4.7,
//     enrollmentCount: 1500,
//     thumbnail:
//       'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
//     category: 'FRONTEND',
//     level: 'ADVANCED',
//     createdAt: '2024-01-15T09:00:00Z',
//     updatedAt: '2024-01-15T09:00:00Z',
//     description:
//       '리액트의 심화 내용을 다루며 상태 관리 라이브러리를 마스터합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-7',
//     title: '파이썬으로 시작하는 데이터 분석',
//     creatorId: 'creator-7',
//     creatorName: '박준형',
//     price: 0,
//     rating: 4.5,
//     enrollmentCount: 2300,
//     thumbnail:
//       'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
//     category: 'AI',
//     level: 'BEGINNER',
//     createdAt: '2024-02-20T10:00:00Z',
//     updatedAt: '2024-02-20T10:00:00Z',
//     description:
//       '파이썬 기초부터 판다스를 활용한 데이터 분석까지 한 번에 배웁니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-8',
//     title: '브랜드 디자인의 모든 것',
//     creatorId: 'creator-8',
//     creatorName: '최수진',
//     price: 0,
//     rating: 4.8,
//     enrollmentCount: 1200,
//     thumbnail:
//       'https://images.unsplash.com/photo-1626785774573-4b799312afc2?q=80&w=2072&auto=format&fit=crop',
//     category: 'GAME',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-03-05T14:00:00Z',
//     updatedAt: '2024-03-05T14:00:00Z',
//     description:
//       '로고부터 패키지 디자인까지, 브랜드 아이덴티티를 구축하는 방법을 배웁니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-9',
//     title: '인스타그램 마케팅 완전 정복',
//     creatorId: 'creator-9',
//     creatorName: '정민수',
//     price: 0,
//     rating: 4.6,
//     enrollmentCount: 3000,
//     thumbnail:
//       'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1974&auto=format&fit=crop',
//     category: 'AI',
//     level: 'BEGINNER',
//     createdAt: '2024-01-10T11:00:00Z',
//     updatedAt: '2024-01-10T11:00:00Z',
//     description: '팔로워를 늘리고 매출로 연결하는 인스타그램 마케팅의 정석.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-10',
//     title: '스타트업 투자 유치 가이드',
//     creatorId: 'creator-10',
//     creatorName: '이준호',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 800,
//     thumbnail:
//       'https://images.unsplash.com/photo-1553729459-efe14ef6055d?q=80&w=2070&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'ADVANCED',
//     createdAt: '2023-12-20T13:00:00Z',
//     updatedAt: '2023-12-20T13:00:00Z',
//     description: 'VC가 알려주는 투자 유치 전략과 IR 피칭 노하우.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-11',
//     title: '스프링 부트 3.0 핵심 가이드',
//     creatorId: 'creator-11',
//     creatorName: '김영한',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 5000,
//     thumbnail:
//       'https://images.unsplash.com/photo-1605379399642-870262d3d051?q=80&w=2106&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-02-01T09:00:00Z',
//     updatedAt: '2024-02-01T09:00:00Z',
//     description:
//       '자바 백엔드 개발의 표준, 스프링 부트 3.0을 깊이 있게 학습합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-12',
//     title: '모션 그래픽 기초: 애프터 이펙트',
//     creatorId: 'creator-12',
//     creatorName: '한소희',
//     price: 0,
//     rating: 4.7,
//     enrollmentCount: 1800,
//     thumbnail:
//       'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2070&auto=format&fit=crop',
//     category: 'GAME',
//     level: 'BEGINNER',
//     createdAt: '2024-03-10T15:00:00Z',
//     updatedAt: '2024-03-10T15:00:00Z',
//     description: '움직이는 그래픽으로 시선을 사로잡는 모션 그래픽 입문 강의.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-13',
//     title: '구글 애널리틱스 4 (GA4) 실전 활용',
//     creatorId: 'creator-13',
//     creatorName: '박성훈',
//     price: 0,
//     rating: 4.5,
//     enrollmentCount: 2500,
//     thumbnail:
//       'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
//     category: 'AI',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-01-25T10:00:00Z',
//     updatedAt: '2024-01-25T10:00:00Z',
//     description: '데이터 기반 마케팅을 위한 GA4 완벽 활용 가이드.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-14',
//     title: '성공적인 협상을 위한 커뮤니케이션 스킬',
//     creatorId: 'creator-14',
//     creatorName: '최지우',
//     price: 0,
//     rating: 4.4,
//     enrollmentCount: 1500,
//     thumbnail:
//       'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=2084&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'BEGINNER',
//     createdAt: '2024-02-15T11:00:00Z',
//     updatedAt: '2024-02-15T11:00:00Z',
//     description: '비즈니스 상황에서 원하는 것을 얻어내는 협상 기술.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-15',
//     title: '도커와 쿠버네티스 완전 정복',
//     creatorId: 'creator-15',
//     creatorName: '정재훈',
//     price: 0,
//     rating: 4.8,
//     enrollmentCount: 2700,
//     thumbnail:
//       'https://images.unsplash.com/photo-1605902711622-cfb43c44367d?q=80&w=2070&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'ADVANCED',
//     createdAt: '2024-01-30T09:30:00Z',
//     updatedAt: '2024-01-30T09:30:00Z',
//     description:
//       '컨테이너 기술의 핵심, 도커와 쿠버네티스를 실전 예제로 완전 정복합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-16',
//     title: 'Next.js 15 완벽 가이드: 프로덕션 레벨 앱 만들기',
//     creatorId: 'inst-1',
//     creatorName: '이영희',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 3420,
//     thumbnail:
//       'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
//     category: 'FRONTEND',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-03-15T09:00:00Z',
//     updatedAt: '2024-03-20T09:00:00Z',
//     description:
//       '최신 Next.js 15의 모든 기능을 마스터하고 실제 상용 서비스를 구축해보는 실전 강의입니다.',
//     curriculum: [
//       {
//         id: 'chapter-1',
//         title: 'Next.js 소개 및 환경 설정',
//         lessons: [
//           {
//             id: 'l-1-1',
//             title: 'Next.js란 무엇인가?',
//             duration: '10:00',
//             type: 'VIDEO',
//           },
//           {
//             id: 'l-1-2',
//             title: '개발 환경 설정하기',
//             duration: '15:30',
//             type: 'VIDEO',
//           },
//         ],
//       },
//       {
//         id: 'chapter-2',
//         title: 'App Router 기초',
//         lessons: [
//           {
//             id: 'l-2-1',
//             title: 'Routing 기본',
//             duration: '12:45',
//             type: 'VIDEO',
//           },
//           {
//             id: 'l-2-2',
//             title: 'Layouts & Templates',
//             duration: '18:20',
//             type: 'VIDEO',
//           },
//           {
//             id: 'l-2-3',
//             title: '퀴즈: App Router 이해도 확인',
//             type: 'QUIZ',
//             questions: [
//               {
//                 id: 'q1',
//                 question: 'App Router는 pages 디렉토리를 대체한다.',
//                 answer: 'O',
//               },
//               {
//                 id: 'q2',
//                 question: 'Server Components는 클라이언트에서 렌더링된다.',
//                 answer: 'X',
//               },
//               {
//                 id: 'q3',
//                 question: 'layout.tsx는 해당 경로의 하위 페이지에 공유된다.',
//                 answer: 'O',
//               },
//             ],
//           },
//         ],
//       },
//     ],
//   },
//   {
//     id: 'lecture-17',
//     title: 'UI/UX 디자인 마스터 클래스: 피그마 기초부터 심화까지',
//     creatorId: 'inst-2',
//     creatorName: '박지성',
//     price: 0,
//     rating: 4.8,
//     enrollmentCount: 2150,
//     thumbnail:
//       'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
//     category: 'GAME', // design → 임시로 GAME
//     level: 'BEGINNER',
//     createdAt: '2024-02-10T14:30:00Z',
//     updatedAt: '2024-02-11T14:30:00Z',
//     description: '피그마 툴 사용법부터 앱 디자인 프로젝트까지 진행합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-18',
//     title: '실전 마케팅 전략: 0원으로 시작하는 그로스 해킹',
//     creatorId: 'inst-3',
//     creatorName: '최민수',
//     price: 0,
//     rating: 4.7,
//     enrollmentCount: 1890,
//     thumbnail:
//       'https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=2074&auto=format&fit=crop',
//     category: 'AI', // marketing → 임시로 AI
//     level: 'ADVANCED',
//     createdAt: '2024-01-20T11:00:00Z',
//     updatedAt: '2024-02-01T11:00:00Z',
//     description: '실전 그로스 해킹 전략을 배웁니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-19',
//     title: '타입스크립트 핸드북: 안전한 자바스크립트 작성하기',
//     creatorId: 'creator-4',
//     creatorName: '김철수',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 5600,
//     thumbnail:
//       'https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=2128&auto=format&fit=crop',
//     category: 'FRONTEND',
//     level: 'BEGINNER',
//     createdAt: '2023-12-05T10:15:00Z',
//     updatedAt: '2023-12-05T10:15:00Z',
//     description:
//       '자바스크립트 개발자라면 필수로 알아야 할 타입스크립트. 기초 문법부터 고급 타입 추론까지 완벽하게 정리해드립니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-20',
//     title: '비즈니스 영어 이메일 작성법',
//     creatorId: 'creator-5',
//     creatorName: 'Sarah Kim',
//     price: 0,
//     rating: 4.6,
//     enrollmentCount: 1200,
//     thumbnail:
//       'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?q=80&w=2070&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'BEGINNER',
//     createdAt: '2024-03-01T09:30:00Z',
//     updatedAt: '2024-03-01T09:30:00Z',
//     description:
//       '글로벌 비즈니스 환경에서 통하는 세련된 영어 이메일 작성법. 상황별 템플릿과 필수 표현을 학습합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-21',
//     title: '실전 리액트 프로그래밍: 리덕스부터 MobX까지',
//     creatorId: 'creator-6',
//     creatorName: '김태희',
//     price: 0,
//     rating: 4.7,
//     enrollmentCount: 1500,
//     thumbnail:
//       'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
//     category: 'FRONTEND',
//     level: 'ADVANCED',
//     createdAt: '2024-01-15T09:00:00Z',
//     updatedAt: '2024-01-15T09:00:00Z',
//     description:
//       '리액트의 심화 내용을 다루며 상태 관리 라이브러리를 마스터합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-22',
//     title: '파이썬으로 시작하는 데이터 분석',
//     creatorId: 'creator-7',
//     creatorName: '박준형',
//     price: 0,
//     rating: 4.5,
//     enrollmentCount: 2300,
//     thumbnail:
//       'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
//     category: 'AI',
//     level: 'BEGINNER',
//     createdAt: '2024-02-20T10:00:00Z',
//     updatedAt: '2024-02-20T10:00:00Z',
//     description:
//       '파이썬 기초부터 판다스를 활용한 데이터 분석까지 한 번에 배웁니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-23',
//     title: '브랜드 디자인의 모든 것',
//     creatorId: 'creator-8',
//     creatorName: '최수진',
//     price: 0,
//     rating: 4.8,
//     enrollmentCount: 1200,
//     thumbnail:
//       'https://images.unsplash.com/photo-1626785774573-4b799312afc2?q=80&w=2072&auto=format&fit=crop',
//     category: 'GAME',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-03-05T14:00:00Z',
//     updatedAt: '2024-03-05T14:00:00Z',
//     description:
//       '로고부터 패키지 디자인까지, 브랜드 아이덴티티를 구축하는 방법을 배웁니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-24',
//     title: '인스타그램 마케팅 완전 정복',
//     creatorId: 'creator-9',
//     creatorName: '정민수',
//     price: 0,
//     rating: 4.6,
//     enrollmentCount: 3000,
//     thumbnail:
//       'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1974&auto=format&fit=crop',
//     category: 'AI',
//     level: 'BEGINNER',
//     createdAt: '2024-01-10T11:00:00Z',
//     updatedAt: '2024-01-10T11:00:00Z',
//     description: '팔로워를 늘리고 매출로 연결하는 인스타그램 마케팅의 정석.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-25',
//     title: '스타트업 투자 유치 가이드',
//     creatorId: 'creator-10',
//     creatorName: '이준호',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 800,
//     thumbnail:
//       'https://images.unsplash.com/photo-1553729459-efe14ef6055d?q=80&w=2070&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'ADVANCED',
//     createdAt: '2023-12-20T13:00:00Z',
//     updatedAt: '2023-12-20T13:00:00Z',
//     description: 'VC가 알려주는 투자 유치 전략과 IR 피칭 노하우.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-26',
//     title: '스프링 부트 3.0 핵심 가이드',
//     creatorId: 'creator-11',
//     creatorName: '김영한',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 5000,
//     thumbnail:
//       'https://images.unsplash.com/photo-1605379399642-870262d3d051?q=80&w=2106&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-02-01T09:00:00Z',
//     updatedAt: '2024-02-01T09:00:00Z',
//     description:
//       '자바 백엔드 개발의 표준, 스프링 부트 3.0을 깊이 있게 학습합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-27',
//     title: '모션 그래픽 기초: 애프터 이펙트',
//     creatorId: 'creator-12',
//     creatorName: '한소희',
//     price: 0,
//     rating: 4.7,
//     enrollmentCount: 1800,
//     thumbnail:
//       'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2070&auto=format&fit=crop',
//     category: 'GAME',
//     level: 'BEGINNER',
//     createdAt: '2024-03-10T15:00:00Z',
//     updatedAt: '2024-03-10T15:00:00Z',
//     description: '움직이는 그래픽으로 시선을 사로잡는 모션 그래픽 입문 강의.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-28',
//     title: '구글 애널리틱스 4 (GA4) 실전 활용',
//     creatorId: 'creator-13',
//     creatorName: '박성훈',
//     price: 0,
//     rating: 4.5,
//     enrollmentCount: 2500,
//     thumbnail:
//       'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
//     category: 'AI',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-01-25T10:00:00Z',
//     updatedAt: '2024-01-25T10:00:00Z',
//     description: '데이터 기반 마케팅을 위한 GA4 완벽 활용 가이드.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-29',
//     title: '성공적인 협상을 위한 커뮤니케이션 스킬',
//     creatorId: 'creator-14',
//     creatorName: '최지우',
//     price: 0,
//     rating: 4.4,
//     enrollmentCount: 1500,
//     thumbnail:
//       'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=2084&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'BEGINNER',
//     createdAt: '2024-02-15T11:00:00Z',
//     updatedAt: '2024-02-15T11:00:00Z',
//     description: '비즈니스 상황에서 원하는 것을 얻어내는 협상 기술.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-30',
//     title: '도커와 쿠버네티스 완전 정복',
//     creatorId: 'creator-15',
//     creatorName: '정재훈',
//     price: 0,
//     rating: 4.8,
//     enrollmentCount: 2700,
//     thumbnail:
//       'https://images.unsplash.com/photo-1605902711622-cfb43c44367d?q=80&w=2070&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'ADVANCED',
//     createdAt: '2024-01-30T09:30:00Z',
//     updatedAt: '2024-01-30T09:30:00Z',
//     description:
//       '컨테이너 기술의 핵심, 도커와 쿠버네티스를 실전 예제로 완전 정복합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-31',
//     title: 'Next.js 15 완벽 가이드: 프로덕션 레벨 앱 만들기',
//     creatorId: 'inst-1',
//     creatorName: '이영희',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 3420,
//     thumbnail:
//       'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
//     category: 'FRONTEND',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-03-15T09:00:00Z',
//     updatedAt: '2024-03-20T09:00:00Z',
//     description:
//       '최신 Next.js 15의 모든 기능을 마스터하고 실제 상용 서비스를 구축해보는 실전 강의입니다.',
//     curriculum: [
//       {
//         id: 'chapter-1',
//         title: 'Next.js 소개 및 환경 설정',
//         lessons: [
//           {
//             id: 'l-1-1',
//             title: 'Next.js란 무엇인가?',
//             duration: '10:00',
//             type: 'VIDEO',
//           },
//           {
//             id: 'l-1-2',
//             title: '개발 환경 설정하기',
//             duration: '15:30',
//             type: 'VIDEO',
//           },
//         ],
//       },
//       {
//         id: 'chapter-2',
//         title: 'App Router 기초',
//         lessons: [
//           {
//             id: 'l-2-1',
//             title: 'Routing 기본',
//             duration: '12:45',
//             type: 'VIDEO',
//           },
//           {
//             id: 'l-2-2',
//             title: 'Layouts & Templates',
//             duration: '18:20',
//             type: 'VIDEO',
//           },
//           {
//             id: 'l-2-3',
//             title: '퀴즈: App Router 이해도 확인',
//             type: 'QUIZ',
//             questions: [
//               {
//                 id: 'q1',
//                 question: 'App Router는 pages 디렉토리를 대체한다.',
//                 answer: 'O',
//               },
//               {
//                 id: 'q2',
//                 question: 'Server Components는 클라이언트에서 렌더링된다.',
//                 answer: 'X',
//               },
//               {
//                 id: 'q3',
//                 question: 'layout.tsx는 해당 경로의 하위 페이지에 공유된다.',
//                 answer: 'O',
//               },
//             ],
//           },
//         ],
//       },
//     ],
//   },
//   {
//     id: 'lecture-32',
//     title: 'UI/UX 디자인 마스터 클래스: 피그마 기초부터 심화까지',
//     creatorId: 'inst-2',
//     creatorName: '박지성',
//     price: 0,
//     rating: 4.8,
//     enrollmentCount: 2150,
//     thumbnail:
//       'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
//     category: 'GAME', // design → 임시로 GAME
//     level: 'BEGINNER',
//     createdAt: '2024-02-10T14:30:00Z',
//     updatedAt: '2024-02-11T14:30:00Z',
//     description: '피그마 툴 사용법부터 앱 디자인 프로젝트까지 진행합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-33',
//     title: '실전 마케팅 전략: 0원으로 시작하는 그로스 해킹',
//     creatorId: 'inst-3',
//     creatorName: '최민수',
//     price: 0,
//     rating: 4.7,
//     enrollmentCount: 1890,
//     thumbnail:
//       'https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=2074&auto=format&fit=crop',
//     category: 'AI', // marketing → 임시로 AI
//     level: 'ADVANCED',
//     createdAt: '2024-01-20T11:00:00Z',
//     updatedAt: '2024-02-01T11:00:00Z',
//     description: '실전 그로스 해킹 전략을 배웁니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-34',
//     title: '타입스크립트 핸드북: 안전한 자바스크립트 작성하기',
//     creatorId: 'creator-4',
//     creatorName: '김철수',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 5600,
//     thumbnail:
//       'https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=2128&auto=format&fit=crop',
//     category: 'FRONTEND',
//     level: 'BEGINNER',
//     createdAt: '2023-12-05T10:15:00Z',
//     updatedAt: '2023-12-05T10:15:00Z',
//     description:
//       '자바스크립트 개발자라면 필수로 알아야 할 타입스크립트. 기초 문법부터 고급 타입 추론까지 완벽하게 정리해드립니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-35',
//     title: '비즈니스 영어 이메일 작성법',
//     creatorId: 'creator-5',
//     creatorName: 'Sarah Kim',
//     price: 0,
//     rating: 4.6,
//     enrollmentCount: 1200,
//     thumbnail:
//       'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?q=80&w=2070&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'BEGINNER',
//     createdAt: '2024-03-01T09:30:00Z',
//     updatedAt: '2024-03-01T09:30:00Z',
//     description:
//       '글로벌 비즈니스 환경에서 통하는 세련된 영어 이메일 작성법. 상황별 템플릿과 필수 표현을 학습합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-36',
//     title: '실전 리액트 프로그래밍: 리덕스부터 MobX까지',
//     creatorId: 'creator-6',
//     creatorName: '김태희',
//     price: 0,
//     rating: 4.7,
//     enrollmentCount: 1500,
//     thumbnail:
//       'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
//     category: 'FRONTEND',
//     level: 'ADVANCED',
//     createdAt: '2024-01-15T09:00:00Z',
//     updatedAt: '2024-01-15T09:00:00Z',
//     description:
//       '리액트의 심화 내용을 다루며 상태 관리 라이브러리를 마스터합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-37',
//     title: '파이썬으로 시작하는 데이터 분석',
//     creatorId: 'creator-7',
//     creatorName: '박준형',
//     price: 0,
//     rating: 4.5,
//     enrollmentCount: 2300,
//     thumbnail:
//       'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
//     category: 'AI',
//     level: 'BEGINNER',
//     createdAt: '2024-02-20T10:00:00Z',
//     updatedAt: '2024-02-20T10:00:00Z',
//     description:
//       '파이썬 기초부터 판다스를 활용한 데이터 분석까지 한 번에 배웁니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-38',
//     title: '브랜드 디자인의 모든 것',
//     creatorId: 'creator-8',
//     creatorName: '최수진',
//     price: 0,
//     rating: 4.8,
//     enrollmentCount: 1200,
//     thumbnail:
//       'https://images.unsplash.com/photo-1626785774573-4b799312afc2?q=80&w=2072&auto=format&fit=crop',
//     category: 'GAME',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-03-05T14:00:00Z',
//     updatedAt: '2024-03-05T14:00:00Z',
//     description:
//       '로고부터 패키지 디자인까지, 브랜드 아이덴티티를 구축하는 방법을 배웁니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-39',
//     title: '인스타그램 마케팅 완전 정복',
//     creatorId: 'creator-9',
//     creatorName: '정민수',
//     price: 0,
//     rating: 4.6,
//     enrollmentCount: 3000,
//     thumbnail:
//       'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1974&auto=format&fit=crop',
//     category: 'AI',
//     level: 'BEGINNER',
//     createdAt: '2024-01-10T11:00:00Z',
//     updatedAt: '2024-01-10T11:00:00Z',
//     description: '팔로워를 늘리고 매출로 연결하는 인스타그램 마케팅의 정석.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-40',
//     title: '스타트업 투자 유치 가이드',
//     creatorId: 'creator-10',
//     creatorName: '이준호',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 800,
//     thumbnail:
//       'https://images.unsplash.com/photo-1553729459-efe14ef6055d?q=80&w=2070&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'ADVANCED',
//     createdAt: '2023-12-20T13:00:00Z',
//     updatedAt: '2023-12-20T13:00:00Z',
//     description: 'VC가 알려주는 투자 유치 전략과 IR 피칭 노하우.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-41',
//     title: '스프링 부트 3.0 핵심 가이드',
//     creatorId: 'creator-11',
//     creatorName: '김영한',
//     price: 0,
//     rating: 4.9,
//     enrollmentCount: 5000,
//     thumbnail:
//       'https://images.unsplash.com/photo-1605379399642-870262d3d051?q=80&w=2106&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-02-01T09:00:00Z',
//     updatedAt: '2024-02-01T09:00:00Z',
//     description:
//       '자바 백엔드 개발의 표준, 스프링 부트 3.0을 깊이 있게 학습합니다.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-42',
//     title: '모션 그래픽 기초: 애프터 이펙트',
//     creatorId: 'creator-12',
//     creatorName: '한소희',
//     price: 0,
//     rating: 4.7,
//     enrollmentCount: 1800,
//     thumbnail:
//       'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2070&auto=format&fit=crop',
//     category: 'GAME',
//     level: 'BEGINNER',
//     createdAt: '2024-03-10T15:00:00Z',
//     updatedAt: '2024-03-10T15:00:00Z',
//     description: '움직이는 그래픽으로 시선을 사로잡는 모션 그래픽 입문 강의.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-43',
//     title: '구글 애널리틱스 4 (GA4) 실전 활용',
//     creatorId: 'creator-13',
//     creatorName: '박성훈',
//     price: 0,
//     rating: 4.5,
//     enrollmentCount: 2500,
//     thumbnail:
//       'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
//     category: 'AI',
//     level: 'INTERMEDIATE',
//     createdAt: '2024-01-25T10:00:00Z',
//     updatedAt: '2024-01-25T10:00:00Z',
//     description: '데이터 기반 마케팅을 위한 GA4 완벽 활용 가이드.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-44',
//     title: '성공적인 협상을 위한 커뮤니케이션 스킬',
//     creatorId: 'creator-14',
//     creatorName: '최지우',
//     price: 0,
//     rating: 4.4,
//     enrollmentCount: 1500,
//     thumbnail:
//       'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=2084&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'BEGINNER',
//     createdAt: '2024-02-15T11:00:00Z',
//     updatedAt: '2024-02-15T11:00:00Z',
//     description: '비즈니스 상황에서 원하는 것을 얻어내는 협상 기술.',
//     curriculum: [],
//   },
//   {
//     id: 'lecture-45',
//     title: '도커와 쿠버네티스 완전 정복',
//     creatorId: 'creator-15',
//     creatorName: '정재훈',
//     price: 0,
//     rating: 4.8,
//     enrollmentCount: 2700,
//     thumbnail:
//       'https://images.unsplash.com/photo-1605902711622-cfb43c44367d?q=80&w=2070&auto=format&fit=crop',
//     category: 'BACKEND',
//     level: 'ADVANCED',
//     createdAt: '2024-01-30T09:30:00Z',
//     updatedAt: '2024-01-30T09:30:00Z',
//     description:
//       '컨테이너 기술의 핵심, 도커와 쿠버네티스를 실전 예제로 완전 정복합니다.',
//     curriculum: [],
//   },
// ];

// export const reviews = [
//   {
//     id: 'r1',
//     lectureId: 'lecture-1',
//     userId: 'u2',
//     nickname: '박지민',
//     rating: 5,
//     createdAt: '2024-03-20',
//     content:
//       'Next.js 15의 새로운 기능을 정말 잘 설명해주십니다. 실무에 바로 적용할 수 있을 것 같아요!',
//   },
//   {
//     id: 'r2',
//     lectureId: 'lecture-1',
//     userId: 'u3',
//     nickname: '최현우',
//     rating: 4,
//     createdAt: '2024-03-18',
//     content:
//       '내용이 알차고 좋습니다. 다만 초보자가 듣기에는 조금 어려울 수 있습니다.',
//   },
//   {
//     id: 'r3',
//     lectureId: 'lecture-2',
//     userId: 'u4',
//     nickname: '이지은',
//     rating: 5,
//     createdAt: '2024-02-15',
//     content:
//       '피그마를 처음 써보는데 강사님이 차근차근 알려주셔서 이해하기 쉬웠어요.',
//   },
// ];
